fe-102 output requirements: browse page, duplicate article pages, improved styling
nicoRDL/dotTheory-FEv2 pull request #2
Opened 2023-02-02 15:55 UTC by nicoRDL

## Description

- adds comment section to article page
- creates browse page
- creates additional duplicate article pages
- linked all pages towards the browse page

## Related Ticket

https://codeandtheory.atlassian.net/browse/FE-649

## Test Instructions

- pull on Fe-102 branch
- evaluate the browse page, duplicate article page, comment section, and styling improvements

## Risks
N/A

2023-02-03 05:07 UTC, lycoangelo requested changes
Hi @nicoRDL, I wrote a couple of minor request changes. And also I found some issues with the PR:
- the detail pages are not styled
- let's restructure the files to mock an actual project

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-detail-page-sample3.html
> +    </div>
It's best practice to use the `footer` tag for footer content.

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-detail-page-light-sample2.html
> +    <div class="footer">
It's best practice to use the `footer` tag for footer content.

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-detail-page-light-sample1.html
> +    <div class="footer">
It's best practice to use the `footer` tag for footer content.

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-browse-page.html
> +    <div class="footer">
It's best practice to use the `footer` tag for footer content.

2023-02-03 05:07 UTC, lycoangelo commented on FE-101/fe101-article-page.html
> +            <input class="comment-button" type="button" value="Comment" />
Use the `button` tag instead for the buttons element.

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-browse-page.html
> +                <input class="form-buttons" type="button" value="Submit" />
Use the `button` tag instead for the buttons element.

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-browse-page.html
> +                <input class="form-buttons" type="reset" value="Reset" />
Use the `button` tag instead for the buttons element.

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-browse-page.html
> +        alt="colored keyboard logo" />
`/>` should be in a new line:
```
<img
  class="nav-logo"
  src="../FE-101/images/keyboard-logo.png"
  alt="colored keyboard logo"
/>
```

Please also check other instances.

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-browse-page.html
> +            target="_blank">
`>` should be in a new line for better readability:
```
<a
  href="https://www.codeandtheory.com/location/manila"
  target="_blank"
>
```

Please also check other instances.

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-browse-page.html
> +              </div>
Instead of wrapping `img` in a `div`, we can wrap it in a `figure` tag instead for better semantic structure.

Please also check other instances.

2023-02-03 05:07 UTC, lycoangelo commented on FE-102/fe-102-browse-page.html
> +        </span>
Let's use a `heading` tag for header elements. Keep in mind the hierarchy order. `h1` should go first, then `h2`, and so on.

Please also check for other instances of this.

2023-02-06 04:35 UTC, nicoRDL commented
@lycoangelo added all code change suggestions and feeback, including new folder and file setup based on suggestion to mimic a sample project 

ba8242938a3dfc6050121e94b09811924ce6a73e

2023-02-06 08:33 UTC, lycoangelo approved these changes

2023-02-06 08:35 UTC, merged