FE-202: Intermediate CSS: Journey Into Mobile (1 of 3)
nicoRDL/dotTheory-FEv2 pull request #4
Opened 2023-02-08 09:57 UTC by nicoRDL

## Description

- update 1 of 3 for FE-202
- updated article pages to be responsive

## Related Ticket

https://codeandtheory.atlassian.net/browse/FE-651

## Testing Instructions

1. Pull on branch Fe-202/FE-651
2. Test responsiveness of Article pages

## Risks
N/A

2023-02-08 10:36 UTC, lycoangelo requested changes

2023-02-08 10:36 UTC, lycoangelo commented on css/main.css
> +@media only screen and (min-width: 64rem) {
Let's use `px` for media query. Browsers also uses pixel unit.

2023-02-08 10:36 UTC, lycoangelo commented on css/main.css
> +@media screen and (min-width: 48rem) {
Let's change unit to pixels.

2023-02-09 07:25 UTC, nicoRDL commented
@lycoangelo changed media query units to pixels 876b3f8f637eb9b8bddc646568f73877a4fda6c1

Also, added the rest of the responsive code for the browse page and home page in said commit for your evaluation.

2023-02-09 08:00 UTC, lycoangelo requested changes

2023-02-09 08:00 UTC, lycoangelo commented on css/home-page.css
> +  }
Indentation was inconsistent. Let's apply two spaces globally instead.

2023-02-09 08:40 UTC, nicoRDL commented on css/home-page.css
> +  }
b66e96c6d42ffa0fe112f188d123a36f4f6cc858 formatting fixed

@lycoangelo

2023-02-09 09:53 UTC, lycoangelo approved these changes

2023-02-09 10:09 UTC, merged