FE-301: Cracking The Case With Flexbox
nicoRDL/dotTheory-FEv2 pull request #5
Opened 2023-02-13 14:27 UTC by nicoRDL

## Description
- implements additional flex box styling to sample site
- updates site structure to fit flex box styling

## Related Ticket
https://codeandtheory.atlassian.net/browse/FE-652

## Testing Instructions
1. Pull on branch FE-301/FE-652
2. Inspect and evaluate use of flex boxes

## Risks
N/A

2023-02-14 07:58 UTC, lycoangelo requested changes

2023-02-14 07:58 UTC, lycoangelo commented on css/home-page.css
> +@media screen and (min-width: 48rem) {
Let's retain the `px` unit for media queries.

2023-02-14 07:58 UTC, lycoangelo commented on css/home-page.css
> +@media screen and (min-width: 64rem) {
Let's retain the `px` unit for media queries.

2023-02-14 08:17 UTC, nicoRDL commented
@lycoangelo added requested changes d9551481e295d2a0ff465fd746ef11f35768535b

d9551481e295d2a0ff465fd746ef11f35768535b

2023-02-14 10:00 UTC, lycoangelo requested changes
Hi @nicoRDL, I left a few comments. Please apply it to the rest of the other implementation.

2023-02-14 10:00 UTC, lycoangelo commented on view/index.html
> +        </header>
We can remove the `header` here and use only the `h1` tag. `h1` is already a heading tag and the `header` tag doesn't add any value to the semantic structure here.

2023-02-14 10:00 UTC, lycoangelo commented on view/index.html
> +          </a>
The same here. We can remove the `h2` tag and use only the `tag`. for proper use of header tags, this link is a good read: https://blog.hubspot.com/marketing/header-tags#:~:text=What%20are%20header%20tags%3F,and%20SEO%20of%20a%20webpage.

2023-02-14 10:00 UTC, lycoangelo commented on view/index.html
> +        </span>
I just checked the page design layout, and this element should be a header tag. Visually, it serves as the header of the Newest Articles.

2023-02-14 10:00 UTC, lycoangelo commented on view/index.html
> +        </a>
[`a`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) and [`button`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) tags should not be a child of any other clickable elements such as `a` and `button` tags.

2023-02-21 07:27 UTC, nicoRDL commented
@lycoangelo added PR change requests and suggestions.
d08d1a0a9cb8b04da7dac8f88f2186731e3ee22a

2023-03-30 08:50 UTC, lycoangelo requested changes

2023-03-30 08:50 UTC, lycoangelo commented on view/browse-page.html
>          </h1>
There should be only 1 `h1` per page. Let's change this to `h2` instead.

2023-03-30 08:50 UTC, lycoangelo commented on view/browse-page.html
> +            </button>
@nicoRDL, there's still plenty of `a` tag inside `button` instances. Please check all the HTML files.

2023-03-30 08:50 UTC, lycoangelo commented on view/browse-page.html
> +              <h2>Lorem Ipsum Dolor sit amet</h2>
Then let's change this to `h3` since we are updating `Continue exploring below` to become an `h3`.

2023-04-05 07:59 UTC, nicoRDL commented
@lycoangelo added all change requests and code improvements, for review

b3b52f20dea348a5137e38d5fb35993fb0ed8a29

2023-04-05 09:54 UTC, lycoangelo requested changes
@nicoRDL,  have left another round of comments pointing out inconsistent indentations.

2023-04-05 09:54 UTC, lycoangelo commented on view/index.html
> +            See More Articles
@nicoRDL, the indentations here are still off.

2023-04-05 09:54 UTC, lycoangelo commented on view/browse-page.html
> +              <a href="detail-page-light-sample1.html" class="article-card-expand-btn">continue reading ...</a>
The indentations here are still off.

2023-04-05 09:54 UTC, lycoangelo commented on view/browse-page.html
> +              <a href="detail-page-light-sample2.html" class="article-card-expand-btn">continue reading ...</a>
The indentations here are still off.

2023-04-05 09:54 UTC, lycoangelo commented on view/index.html
> +              <a href="detail-page-sample1.html" class="article-card-expand-btn">continue reading ...</a>
The indentations here are still off.

2023-04-05 09:54 UTC, lycoangelo commented on view/index.html
> +              <a href="detail-page-sample2.html" class="article-card-expand-btn">continue reading ...</a>
The indentations here are still off.

2023-04-05 09:54 UTC, lycoangelo commented on view/index.html
> +              <a href="detail-page-sample3.html" class="article-card-expand-btn">continue reading ...</a>
The indentations here are still off.

2023-04-05 09:54 UTC, lycoangelo commented on view/browse-page.html
> +              <a href="detail-page-light-sample1.html" class="article-card-expand-btn">continue reading ...</a>
The indentations here are still off.

2023-04-05 09:54 UTC, lycoangelo commented on view/browse-page.html
> +              <a href="detail-page-light-sample2.html" class="article-card-expand-btn">continue reading ...</a>
The indentations here are still off.

2023-04-05 09:54 UTC, lycoangelo commented on view/browse-page.html
> +              <a href="detail-page-light-sample1.html" class="article-card-expand-btn">continue reading ...</a>
The indentations here are still off.

2023-04-05 10:32 UTC, nicoRDL commented
@lycoangelo noted on the spacing and indention issues. Re-applied the formatter on the target pages, hopefully it fixes all the errors. For your re-review

https://github.com/nicoRDL/dotTheory-FEv2/pull/5/commits/415e18d7a2091249ec65b5017f5559c2fc529abf

2023-04-05 10:36 UTC, merged