FE-401: Assembling Sass
nicoRDL/dotTheory-FEv2 pull request #6
Opened 2023-08-16 10:23 UTC by nicoRDL

## Description
- refactors css files to scss files, converting to Sass
- refactors view files to sass convertions in styles

## Related Ticket
https://codeandtheory.atlassian.net/browse/FE-654

## Testing Instructions
1. Pull on branch FE-401/FE-654
2. Evaluate the use of Sass in the stylesheets
3. Confirm that website and all web pages are showing correct styles from previous css implementation

## RIsks
N/A

2023-09-02 15:38 UTC, lycoangelo requested changes
@nicoRDL, great work overall! I have a challenge for you to further enhance the code. Can you please consider implementing the BEM (Block Element Modifier) methodology? You can learn more about it here: [BEM Methodology Quick Start](https://en.bem.info/methodology/quick-start/).

This will help improve code structure and maintainability by providing a clear naming convention for your CSS classes and making your styles more modular.

2023-09-04 07:35 UTC, nicoRDL commented
@lycoangelo noted on the enhancement work. Fully applied BEM methodology to sample website here 68cf8296104a11d08e15e1b34aa84a210c82ea35

For re-review. Thanks!

2023-09-04 12:08 UTC, lycoangelo requested changes
@nicoRDL, To implement the BEM methodology, you should name your HTML elements with specific classes following the `block__element--modifier` pattern, where the double underscore `__` signifies an element within the block, and the double hyphen `--` denotes a modifier that alters the appearance or behavior of the block or element, ensuring clear separation of concerns and a well-structured approach to styling.

2023-09-04 12:08 UTC, lycoangelo commented on scss/components/_typography.scss
> +.user-comment__card {
Let's avoid duplicating classes; if this can be considered as another component, combine this styling with the one from the `container.scss`.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_containers.scss
> +  &-browse {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/components/_buttons.scss
> +  &-section-expand-btn {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/components/_typography.scss
> +  &-container-header {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_containers.scss
> +  &-container {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_containers.scss
> +  &-container {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_containers.scss
> +  &-section {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_containers.scss
> +  &-container {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_containers.scss
> +  &-container {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_nav.scss
> +  &-browse {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_nav.scss
> +  &-homepage {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_nav.scss
> +  &-lip {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_nav.scss
> +    &-browse {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_nav.scss
> +    &-home {
Please apply the BEM methodology here as well.

2023-09-04 12:08 UTC, lycoangelo commented on scss/layout/_nav.scss
> +    &-link {
Please apply the BEM methodology here as well.

2023-09-05 08:46 UTC, merged